#!/usr/bin/env bash

# Some items learn their aggregator late in life.

echo -e "
a += b * c.
rules
b := 2.
rules
c := 3.
rules" |./dyna > $0.out

diff <(sed -e 's/[ -][^ -]*\/\.dyna/ /g' $0.expect) \
     <(sed -e 's/[ -][^ -]*\/\.dyna/ /g' $0.out)    \
 && echo pass
